CREATE TABLE IF NOT EXISTS deaths(
PROVINCE_STATE text,
COUNTRY_REGION text,
LATITUDE float,
LONGITUDE float,
ACUMULATED int,
DATE date,
DELTA int
);

CREATE TABLE IF NOT EXISTS recovered(
PROVINCE_STATE text,
COUNTRY_REGION text,
LATITUDE float,
LONGITUDE float,
ACUMULATED int,
DATE date,
DELTA int
);

CREATE TABLE IF NOT EXISTS confirmed(
PROVINCE_STATE text,
COUNTRY_REGION text,
LATITUDE float,
LONGITUDE float,
ACUMULATED int,
DATE date,
DELTA int
);